sudo: required

language: generic

services:
 - docker

before_install:
 - echo "start Creating an image with dockerfile"
 - docker build -t oopswhdals/docker-react-app -f Dockerfile.dev .

script:
 - docker run -e CI=true oopswhdals/docker-react-app npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "ap-northeast-2"
 app: "docker-react-app"
 env: "docker-react-app"
 bucket_name: "elasticbeanstalk-ap-northeast-2-541662912292"
 bucket_path: "docker-react-app"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key_id: $AWS_SECRET_ACCESS_KEY